// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "search_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* search_msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  search_msg_reflection_ = NULL;
const ::google::protobuf::Descriptor* search_result_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  search_result_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_search_5fmsg_2eproto() {
  protobuf_AddDesc_search_5fmsg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "search_msg.proto");
  GOOGLE_CHECK(file != NULL);
  search_msg_descriptor_ = file->message_type(0);
  static const int search_msg_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(search_msg, word_),
  };
  search_msg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      search_msg_descriptor_,
      search_msg::default_instance_,
      search_msg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(search_msg, _has_bits_[0]),
      -1,
      -1,
      sizeof(search_msg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(search_msg, _internal_metadata_),
      -1);
  search_result_descriptor_ = file->message_type(1);
  static const int search_result_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(search_result, id_),
  };
  search_result_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      search_result_descriptor_,
      search_result::default_instance_,
      search_result_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(search_result, _has_bits_[0]),
      -1,
      -1,
      sizeof(search_result),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(search_result, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_search_5fmsg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      search_msg_descriptor_, &search_msg::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      search_result_descriptor_, &search_result::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_search_5fmsg_2eproto() {
  delete search_msg::default_instance_;
  delete search_msg_reflection_;
  delete search_result::default_instance_;
  delete search_result_reflection_;
}

void protobuf_AddDesc_search_5fmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020search_msg.proto\"\032\n\nsearch_msg\022\014\n\004word"
    "\030\001 \003(\014\"\033\n\rsearch_result\022\n\n\002id\030\001 \003(\005", 75);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "search_msg.proto", &protobuf_RegisterTypes);
  search_msg::default_instance_ = new search_msg();
  search_result::default_instance_ = new search_result();
  search_msg::default_instance_->InitAsDefaultInstance();
  search_result::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_search_5fmsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_search_5fmsg_2eproto {
  StaticDescriptorInitializer_search_5fmsg_2eproto() {
    protobuf_AddDesc_search_5fmsg_2eproto();
  }
} static_descriptor_initializer_search_5fmsg_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int search_msg::kWordFieldNumber;
#endif  // !_MSC_VER

search_msg::search_msg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:search_msg)
}

void search_msg::InitAsDefaultInstance() {
}

search_msg::search_msg(const search_msg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:search_msg)
}

void search_msg::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

search_msg::~search_msg() {
  // @@protoc_insertion_point(destructor:search_msg)
  SharedDtor();
}

void search_msg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void search_msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* search_msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return search_msg_descriptor_;
}

const search_msg& search_msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_search_5fmsg_2eproto();
  return *default_instance_;
}

search_msg* search_msg::default_instance_ = NULL;

search_msg* search_msg::New(::google::protobuf::Arena* arena) const {
  search_msg* n = new search_msg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void search_msg::Clear() {
  word_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool search_msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:search_msg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bytes word = 1;
      case 1: {
        if (tag == 10) {
         parse_word:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_word()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_word;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:search_msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:search_msg)
  return false;
#undef DO_
}

void search_msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:search_msg)
  // repeated bytes word = 1;
  for (int i = 0; i < this->word_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->word(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:search_msg)
}

::google::protobuf::uint8* search_msg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:search_msg)
  // repeated bytes word = 1;
  for (int i = 0; i < this->word_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(1, this->word(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:search_msg)
  return target;
}

int search_msg::ByteSize() const {
  int total_size = 0;

  // repeated bytes word = 1;
  total_size += 1 * this->word_size();
  for (int i = 0; i < this->word_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->word(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void search_msg::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const search_msg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const search_msg>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void search_msg::MergeFrom(const search_msg& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  word_.MergeFrom(from.word_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void search_msg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void search_msg::CopyFrom(const search_msg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool search_msg::IsInitialized() const {

  return true;
}

void search_msg::Swap(search_msg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void search_msg::InternalSwap(search_msg* other) {
  word_.UnsafeArenaSwap(&other->word_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata search_msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = search_msg_descriptor_;
  metadata.reflection = search_msg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// search_msg

// repeated bytes word = 1;
int search_msg::word_size() const {
  return word_.size();
}
void search_msg::clear_word() {
  word_.Clear();
}
 const ::std::string& search_msg::word(int index) const {
  // @@protoc_insertion_point(field_get:search_msg.word)
  return word_.Get(index);
}
 ::std::string* search_msg::mutable_word(int index) {
  // @@protoc_insertion_point(field_mutable:search_msg.word)
  return word_.Mutable(index);
}
 void search_msg::set_word(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:search_msg.word)
  word_.Mutable(index)->assign(value);
}
 void search_msg::set_word(int index, const char* value) {
  word_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:search_msg.word)
}
 void search_msg::set_word(int index, const void* value, size_t size) {
  word_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:search_msg.word)
}
 ::std::string* search_msg::add_word() {
  return word_.Add();
}
 void search_msg::add_word(const ::std::string& value) {
  word_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:search_msg.word)
}
 void search_msg::add_word(const char* value) {
  word_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:search_msg.word)
}
 void search_msg::add_word(const void* value, size_t size) {
  word_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:search_msg.word)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
search_msg::word() const {
  // @@protoc_insertion_point(field_list:search_msg.word)
  return word_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
search_msg::mutable_word() {
  // @@protoc_insertion_point(field_mutable_list:search_msg.word)
  return &word_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int search_result::kIdFieldNumber;
#endif  // !_MSC_VER

search_result::search_result()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:search_result)
}

void search_result::InitAsDefaultInstance() {
}

search_result::search_result(const search_result& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:search_result)
}

void search_result::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

search_result::~search_result() {
  // @@protoc_insertion_point(destructor:search_result)
  SharedDtor();
}

void search_result::SharedDtor() {
  if (this != default_instance_) {
  }
}

void search_result::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* search_result::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return search_result_descriptor_;
}

const search_result& search_result::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_search_5fmsg_2eproto();
  return *default_instance_;
}

search_result* search_result::default_instance_ = NULL;

search_result* search_result::New(::google::protobuf::Arena* arena) const {
  search_result* n = new search_result;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void search_result::Clear() {
  id_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool search_result::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:search_result)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 id = 1;
      case 1: {
        if (tag == 8) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_id())));
        } else if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_id())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(8)) goto parse_id;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:search_result)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:search_result)
  return false;
#undef DO_
}

void search_result::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:search_result)
  // repeated int32 id = 1;
  for (int i = 0; i < this->id_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->id(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:search_result)
}

::google::protobuf::uint8* search_result::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:search_result)
  // repeated int32 id = 1;
  for (int i = 0; i < this->id_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->id(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:search_result)
  return target;
}

int search_result::ByteSize() const {
  int total_size = 0;

  // repeated int32 id = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->id_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->id(i));
    }
    total_size += 1 * this->id_size() + data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void search_result::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const search_result* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const search_result>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void search_result::MergeFrom(const search_result& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  id_.MergeFrom(from.id_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void search_result::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void search_result::CopyFrom(const search_result& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool search_result::IsInitialized() const {

  return true;
}

void search_result::Swap(search_result* other) {
  if (other == this) return;
  InternalSwap(other);
}
void search_result::InternalSwap(search_result* other) {
  id_.UnsafeArenaSwap(&other->id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata search_result::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = search_result_descriptor_;
  metadata.reflection = search_result_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// search_result

// repeated int32 id = 1;
int search_result::id_size() const {
  return id_.size();
}
void search_result::clear_id() {
  id_.Clear();
}
 ::google::protobuf::int32 search_result::id(int index) const {
  // @@protoc_insertion_point(field_get:search_result.id)
  return id_.Get(index);
}
 void search_result::set_id(int index, ::google::protobuf::int32 value) {
  id_.Set(index, value);
  // @@protoc_insertion_point(field_set:search_result.id)
}
 void search_result::add_id(::google::protobuf::int32 value) {
  id_.Add(value);
  // @@protoc_insertion_point(field_add:search_result.id)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
search_result::id() const {
  // @@protoc_insertion_point(field_list:search_result.id)
  return id_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
search_result::mutable_id() {
  // @@protoc_insertion_point(field_mutable_list:search_result.id)
  return &id_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
