# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='index_msg.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0findex_msg.proto\"\'\n\nSingleItem\x12\x0c\n\x04item\x18\x01 \x02(\x0c\x12\x0b\n\x03num\x18\x02 \x01(\r\"=\n\tindex_msg\x12\x0e\n\x06max_id\x18\x01 \x02(\x04\x12 \n\x0bsingle_item\x18\x02 \x03(\x0b\x32\x0b.SingleItem')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SINGLEITEM = _descriptor.Descriptor(
  name='SingleItem',
  full_name='SingleItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='SingleItem.item', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='SingleItem.num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=58,
)


_INDEX_MSG = _descriptor.Descriptor(
  name='index_msg',
  full_name='index_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_id', full_name='index_msg.max_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='single_item', full_name='index_msg.single_item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=121,
)

_INDEX_MSG.fields_by_name['single_item'].message_type = _SINGLEITEM
DESCRIPTOR.message_types_by_name['SingleItem'] = _SINGLEITEM
DESCRIPTOR.message_types_by_name['index_msg'] = _INDEX_MSG

SingleItem = _reflection.GeneratedProtocolMessageType('SingleItem', (_message.Message,), dict(
  DESCRIPTOR = _SINGLEITEM,
  __module__ = 'index_msg_pb2'
  # @@protoc_insertion_point(class_scope:SingleItem)
  ))
_sym_db.RegisterMessage(SingleItem)

index_msg = _reflection.GeneratedProtocolMessageType('index_msg', (_message.Message,), dict(
  DESCRIPTOR = _INDEX_MSG,
  __module__ = 'index_msg_pb2'
  # @@protoc_insertion_point(class_scope:index_msg)
  ))
_sym_db.RegisterMessage(index_msg)


# @@protoc_insertion_point(module_scope)
